USE mysql
DROP DATABASE IF EXISTS hospital_registry;
CREATE DATABASE hospital_registry;
USE hospital_registry;

CREATE TABLE IF NOT EXISTS PATIENTS(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(60) NOT NULL,
    egn VARCHAR(60) NOT NULL UNIQUE,
    age INT NOT NULL,
    diagnosis VARCHAR(60) NOT NULL,
    prognosis VARCHAR(10) NOT NULL
);

CREATE TABLE IF NOT EXISTS DEATH_PATIENTS(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(60) NOT NULL,
    egn VARCHAR(60) NOT NULL UNIQUE
);